version: "3"
services:
  nginx:
    ports:
      - "3001:80"
  node-loginapi:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=root
      - MONGO_PASSWORD=Passw0rd
      - SESSION_SECRET=secret
    command: npm run dev