version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3001:80"
    volumes:
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-loginapi
  node-loginapi:
#   container_name: node-loginapi
    build: .
    image: node-loginapi:latest
#    ports:
#     - "3001:3001"
    environment:
      - PORT=3001
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - mongo-db:/data/db
  redis:
    container_name: redis
    image: redis:latest

volumes:
  mongo-db: