version: "3"
services:
  node-app:
    container_name: loginapi
    build: .
    image: nodejs-loginapi:latest
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Passw0rd
    volumes:
      - mongo-db:/data/db
  redis:
    container_name: redis
    image: redis:latest

volumes:
  mongo-db: